### ISSUE TITLE
Does this passthrough support arming over Bluetooth from QCG?

### ISSUE THREAD

**Issue by mattgorski** [zs6buj/Frsky2Mavlink#1]
Found this git source link from here:
https://www.rcgroups.com/forums/showthread.php?3089648-Mavlink-To-FrSky-Passthrough-Converter/page5

I am using the Frsky R9/R9M Long Range UHF combo and I'd like a way to view Mavlink messages over BT HC-06 in QGC and bypass the need for a Sik radio for arming and disarming.

Would this project work for what I am trying to accomplish?  Also what modifications are needed to use this on a Teensy 3.2?

Thanks for your work on this and hopefully we can improve on its functionality.

**Comment by zs6buj** [comment]
Hi Matt

Sorry for the tardy response. I've been away on holiday and finally catching up with correspondence. :)

This project, as it stands, converts FrSky telemetry to the Mavlink 1 protocol. Since FrSky sends telemetry one way only, from the craft back to the Taranis, there is no way with this configuration to send arming or flight mode commands to the FC on the craft.

I recently acquired a R9/R9M pair (as part of a Horus promotion by horusrc.com), so when I get around to playing with those transceivers I'll think about your request. Maybe we could use an unused rc channel. Have you looked at EZ-Wifibroadcast, using rc on 2.4GHz or 5GHz with full mavlink telemetry and pretty good range. Oh, and not least, full HD video.
